name: "Get & Cache dependencies"
description: "Get and cache dependencies via npm and cache them"
inputs:
  caching:
    description: "Wheter to cache dependencies or not."
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Wheter the cache was used or not."
    value: ${{ steps.install.outputs.step-result }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: install
      run: |
        npm ci
        echo 'step-result=${{ inputs.caching }}' >> $GITHUB_OUTPUT ';'
      shell: bash # must be added for run action inside composite action
