name: 02 Basics - Practice Step1
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --prefix Code/02\ Basics/04\ Practice\ Project\ \(Start\)
      - name: Run lint
        run: npm run lint --prefix Code/02\ Basics/04\ Practice\ Project\ \(Start\)
      - name: Run tests
        run: npm test --prefix Code/02\ Basics/04\ Practice\ Project\ \(Start\)
      - name: Run build
        run: npm run build --prefix Code/02\ Basics/04\ Practice\ Project\ \(Start\)
