name: Matrix Workflow
on: push
jobs:
  php:
    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.2
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - php-version: 8.1
            os: ubuntu-latest
        exclude:
          - php-version: 8.2
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Php
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Print php version
        run: echo ${{ steps.setup-php.outputs.php-version }}
