name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: The name of de the deployable artifact files
        required: false
        default: "dist"
    outputs:
      result:
        description: The result of the deployment
        value: ${{ jobs.deploy.outputs.job-result }}
    secrets:
      token:
        description: The Github token
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      job-result: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: Output result
        id: set-result
        run: echo 'step-result=success' >> $GITHUB_OUTPUT ';'
