name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: The name of de the deployable artifact files
        required: false
        default: "dist"
    secrets:
      token:
        description: The Github token
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
